### ISSUE TITLE
ImportError: DLL load failed while importing _eyerec

### ISSUE THREAD

**Issue by Serif-NNR** [tcsantini/eyerec-python#2]
Hello,

I have installed eyerec using Python 3.10 from pip repos, then tried to import it as "import eyerec".
However, I faced the following error on Windows 10:
`Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import eyerec
  File "C:\Program Files\Python310\lib\site-packages\eyerec\__init__.py", line 1, in <module>
    from ._eyerec import PupilTracker
ImportError: DLL load failed while importing _eyerec: The specified module could not be found.`
Additionally, Google Colab doesn't support to install the library from pip.

How can I surpass the error and use the library for PuRe method? 
Note: I tried to import eyerec with pyximport, but the issue wasn't solved.

Thanks

**Comment by AIMUWEITING** [comment]
I'm having the same problem, have you solved it?

**Comment by tcsantini** [comment]
I assume this is about the eyerec package in PyPI? Please note that it isn't maintained by me and not officially related to this project.

Please contact the package maintainer: https://pypi.org/project/eyerec/#data

**Comment by serifinanir** [comment]
> I'm having the same problem, have you solved it?

Heya,
I have used to PuRe implementation written with C++. If you should prefer Python, 
maybe a C++ lib to be imported by your Py script can be prepared for it.
I assume too this is related to dep packages. 
Cheers
